### ISSUE TITLE
Horizontal spacing broken for all themes

### ISSUE THREAD

**Issue by Ramdat** [cameroncondry/cbc-kitten-scientists#141]
Horizontal spacing for all themes except Sleek does not stretch to the full screen size. Although Sleek does stretch the entire width, it does not properly adjust the middle to use this space, so the empty space is between the buildings and log instead of on the right side. 

[Without script, Vanilla](http://i.imgur.com/tec8A60.png)
[With script, Classic](http://i.imgur.com/qnYpOW3.png)
[With script, Inverted](http://i.imgur.com/6cgedJw.png)
[With script, Grass](http://i.imgur.com/myZq7b7.png)
[With script, Sleek](http://i.imgur.com/1Yb1Er0.png)
[KS version 1.2.4 working as intended](http://i.imgur.com/6yBbFlC.png)
No version past 1.2.4 appears to work correctly. 

The "enable KS" checkbox is not checked because I removed it to take the vanilla screenshot and then forgot to enable it for the others. Checking the box has no effect on the spacing.

**Comment by oliversalzburg** [comment]
Oh damn, seems like I messed this up when I submitted one of my patches. Sorry for that. Will fix this when my other PRs are merged.

**Comment by oliversalzburg** [comment]
I fixed this over at https://github.com/oliversalzburg/cbc-kitten-scientists/tree/fix/141

I originally made that change in my own fork, because the full-width is not very nice to use on large resolutions. Then I messed up the patch when making the adjustments for the Sleek theme.

Either way, this should be fixed soon. All the hard-coded adjustments I made in my own fork are now properly integrated here and I'm also no longer using my fork.
