### ISSUE TITLE
Does not craft eludium

### ISSUE THREAD

**Issue by doug-w** [cameroncondry/cbc-kitten-scientists#234]
How do I debug what is being crafted or not?  My Scientists aren't crafting Eludium.  My stats:

I'm currently running with 1242/1242 unobtanium, 18.93k alloy.  
Crafting of steel is enabled/not limited, Alloy enabled/limited, Eludium Enabled/Not Limited. 
I removed all resource stockpiles, I've left the item trigger at .9.

Any ideas of either why it's not crafting or the best way to go about debugging it?

**Comment by Blauelf** [comment]
Click the "resources" button on crafting. Chances are you reserve some Unobtainium. Not sure whether Eludium makes much sense when you have such low resource caps.

**Comment by Eusebius** [comment]
I seem to have a similar issue, eludium is never crafted even when I have a higher unobtainium cap (and loads of alloy). I've tried to play with the resource settings in the crafting section, but nothing seems to work (and I'm going a bit random with those settings since it is very hard for me to understand what they are supposed to do).

For instance, right now I have a 17k unobtainium cap, 4M of alloy, 5000 "stock" and 0.5 "consume" in the unobtainium resource settings, and eludium set to be crafted as an item without a seasonal limit. And I've never seen it crafted.

**Comment by Wymrite** [comment]
Appears to no longer be an issue in the current crafting system, likely was a result of the enable-all issue.
