### ISSUE TITLE
Update Ver 1.0.7.3 renders autobuild function useless

### ISSUE THREAD

**Issue by mgm518** [cameroncondry/cbc-kitten-scientists#29]
Essentially, whenever scientists tries to auto-build, I get this error in my console:
TypeError: event is undefined
http://bloodrizer.ru/games/kittens/buildings.js?v=1.0.7.3b
Line 1552

Though it is within the main game's own javascript, this error only pops up when scientists is active, as I can build fine without errors with/without scientists.  I think it will start working again if the auto-build function also implemented the shift key as well.

**Comment by cameroncondry** [comment]
This looks to be a bug in the latest PR I merged in. I will see what I can do to clean up this issue, thank you for reporting!

**Comment by cameroncondry** [comment]
This has been corrected by a temporary fix on the master branch. @sjdrodge I see you're working on a correction as well. I noticed a "build" method in the onClick for the building manager, I am going to play with the idea of using that method directly. Previously I wasn't able to build with that method because it would not expend resources.

**Comment by sjdrodge** [comment]
@cameroncondry I think the approach taken in my patch is actually a good general solution to the problem (it simply uses jQuery to click buttons, which will generate valid event objects). As for using the build function directly, there are a few problems with that, as some of the important game-state updates are handled directly in onClick. Anyway, I think you should consider reverting your solution, and applying mine instead (as well as incorporating it into your current development branch).

**Comment by cameroncondry** [comment]
@sjdrodge I will probably use your proposed solution for now on the master branch since it looks at other onClick events. I've found that, at least in the case of praising, that you can completely skip the interface by using a more obscure method in the code.

**Comment by sjdrodge** [comment]
@cameroncondry Are you talking about using `game.religion.praise()` as we used to in commit 1b06737? because unfortunately, when I tried the same approach for festivals in 97258c3, we ended up not paying festival costs. From my reading of the code, there's no real clean way to call button handler functions directly except in the case of praising, so, for the sake of consistency, I made praising also operate via clicking in commit 025afb3.

**Comment by jacob-keller** [comment]
Yes I agree here. As long as we can do it without having to be on the tab
directly...

**Comment by cameroncondry** [comment]
@sjdrodge that is a good point, but working with the buttons themselves have some easy ways to check resources then use the onclick btn handler, which doesn't require event data. I'm very back and forth, but in general, my commits on the optional-crafting have what I'm currently working on improving.
