### ISSUE TITLE
feature branch trading 

### ISSUE THREAD

**Issue by jacob-keller** [cameroncondry/cbc-kitten-scientists#31]
Trading does not honor catpower/gold resource limits in the feature branch. This causes issues because as long as the resource we are obtaining isn't capped we will spend all of our gold and catpower on trading. Maybe this isn't bad, except:

we only craft luxury resources if we're hunting, so we never ever hunt if we trade (and the resources we are trading for are not capped). Since luxury goods take such items as science and culture, we can't craft them later. (since we need to craft them as the cap fills).

ideally:

1) we wouldn't trade unless we also have enough stocked resources as well as catpower and gold.

2) once we have enough control over resource stocks, we should move luxury crafting out as a step that takes place prior to hunting, and honors stock limits to ensure we maintain enough of each resource. This way we continue to craft things like compendiums, manuscripts and blueprints as their c constrained resource allows instead of only ever crafting these when we have resources to hunt. Especially since hunting costs a lot of catpower and won't occur as fast as we accumulate culture and science, etc.

**Comment by cameroncondry** [comment]
I noticed that with trading and should have a fix in the near future. I've been idling with the updates for a few days while I've been unable to contribute to the code base. Once stocks are able to be fine tuned, then I think the idea of moving those items out of the "luxury" category would work out well. Currently, however, they just drain like no tomorrow when activated outside hunting.

**Comment by jacob-keller** [comment]
Yea. That's why you need stocks =]

**Comment by jacob-keller** [comment]
Right now what it does is sort of a logrithmic trade where it trades "half catpower and gold" and then half again in5 seconds and repeat.

I don't know the best way to fix these  interactions, because we want to allow both hunting and trading and such. Here's a way maybe to resolve this in a general solution:

the main goal of kittens scientists is to automate the tasks which a player could do while active, but could not do by returning to an idle session.

We want to focus primarily on doing things which are resource constrained, ie: constrained on some resource like catpower or science or so forth.

What we've had so far (before the introduction of things like trading) has been that we only do "one" thing per resource, or we do two kinds of things which tend not to interfere such as housing/buildings which very quickly escape our current caps and thus don't crowd out general goods making.

So what if for the other items (trading/hunting combos etc)

we create "triggers" like "catpower reaches xyz" and that triggers certain actions like "trading" and "hunting"

instead of doing a "winner takes all" or a first-come-first-serve deal, we could split between the available resources. This is obviously somewhat less clear in a dual-resource situation, but at least would help some of the impact.

The alternative would be to not consume a large portion of the resources at oncec, and instead go "check if everything is full up front and then only trade once, and only hunt once (not sure that's possible actually....), and so on. This way, if we cap catpower, we will trade once and hunt once, and then re-do this again when it recaps.

This would create more fluid results, I think.

Obviously the main issues with this approach is getting the numbers correct,, and that requires configuration ability.

**Comment by cameroncondry** [comment]
I don't disagree that will help make the results more fluid. However, I do think that is a bit overkill at this time with stocks in the pipeline. Manually altering the stocks in the command line makes it manageable to do things like trading and crafting special resources. Only big issue I see currently is there is a lot more micromanagement with the system, since as requirements grow, the player is forced to continue updating stock limits.

I've also avoided allowing multiple resource triggers simply due to the infrequency crafts and builds happen when so many options are vying for the same resource caps. Trading requiring catpower and gold is a good example, since catpower is used with hunting and gold is used on  buildings. This makes it a mildly rare occurrence that both resources hit the trigger cap.

With that, I do see potential for a reporting feature that would make it possible to allow all automation to use the pools equally. It would consist of dividing up the available resources on trigger and allotting the various items a specific amount, then outputting the results over the period of time it starts reporting.

**Comment by jacob-keller** [comment]
The problem right now is starvation of either trading or hunting. And
starving hunting means zero luxury goods

Stocks can be set fairly reasonable I think and only modified when working
towards a large goal

**Comment by trini** [comment]
I think this shows frankly that "luxury" is just wrong.  I've ripped it out of my local fork and manually manage the stock limits on parchment, manuscript and compendium and then let crafting happen.

**Comment by cameroncondry** [comment]
I agree, and have been letting the system run with the luxury items, minus parchment, get crafted continuously while the crafting check box is selected. It eats resources, but when you have enough, just toggle it back off. However, it does kill some of the automation that you get when the system is allowed to craft luxury items during hunts.

**Comment by jacob-keller** [comment]
The ones that matter most are resource bounded on science and culture.

**Comment by cameroncondry** [comment]
I just about have this update wrapped up and have decided not to tackle stocks this update since I've already taken this long to finish the update. Currently luxury items will still be built during hunts, and stocks work for resource trading. However, buildings will no honor stocks currently. Should have a stable build up soon (tm).
