### ISSUE TITLE
Capped resource crafting is Seasonal

### ISSUE THREAD

**Issue by Mewnine** [cameroncondry/cbc-kitten-scientists#41]
Capped resources are currently also crafting once per season instead of always crafting at 95%

**Comment by cameroncondry** [comment]
Currently that is by design. It attempts to give the chance of other items to craft/build, which was being starved due to the sheer number of items that can build, craft, and trade. There may need to be a special bypass on some resources, like catnip to wood, since I am seeing a few of the resources stay capped that could easily refine into something else.

**Comment by jacob-keller** [comment]
It should only stop resources require something that isn't capped. Maybe we
have it backwards

**Comment by jacob-keller** [comment]
I think we made a mistake in the previous example, we should have said maxValue !== 0.. I like your idea better though. We can easily add a toggle next to each resource that shows if it is limited or not.
