### ISSUE TITLE
how to create pop-up dialogs?

### ISSUE THREAD

**Issue by jacob-keller** [cameroncondry/cbc-kitten-scientists#43]
I'm interested in adding cap/stock popups via on-click actions from the labels. I don't know how to create pop-up dialogs though.

I assume that there is some way as the game does this in various ways. I think it's probably the cleanest way to ask for user input on stock and max values.

I'd like to be able to make these configurable so that we can more easily support various game states. Maybe then we can also have some preset defaults for stages of the game.

An alternative is to be able to serialize and deserialize the options, most probably using json or compressed json format? Javascript has some great ways to read this in I believe. I don't know if we want to store these in settings somehow or maybe some sort of cookie of our own?

It might just be best to store these as text the user can import and export.

Anyways, these are probably the next big enhancement projects that I'd like to try my hand at.

**Comment by cameroncondry** [comment]
I like the idea of game states for different stages in the game. Could tie that to income or something stable since paragon alters the time frame on when you should make certain actions.

There is a system pop up for the game settings, but I'm not sure how reusable that is. However, it isn't too hard to create a floating element that you can input information into. I'm not sure about using pop ups though because that can easily get intrusive for the user.

As for saving, I've been thinking a bit on it since I started the script, and the best option for now is going to be a simple json format either in local storage or cookies. We will want to store it in a separate entry either way, just to keep things clean. The options should be the only requirement for saving the information, just would need to create a function to pull the information out of storage and apply the settings. In the future might work on some compression of the data, but there is very minimal information needed to get the script up and running that it shouldn't be a priority.

**Comment by jacob-keller** [comment]
Personally just exporting options as json and versioning the options is the
simplest way. Probably want to wait till we have everything stabl enough
though.

I mostly was thinking floating frames for input of stock and such. Much
like how buildings show hovered dialogs
