### ISSUE TITLE
Efficiency tweaks to trading and crafting

### ISSUE THREAD

**Issue by Mewnine** [cameroncondry/cbc-kitten-scientists#46]
At the moment, to make sure I use up all my gold I have to deactivate hunting. This means I am also not converting my furs into parchments when I leave the game on for a night, so I have to save up parchment beforehand while my mints could cover most of it. And I'm still losing gold and catpower.

A few tweaks could improve the system:
Trading whenever the gold cap would be close and ignoring the catpower cap would mean that all gold gets used and any overflow would go to hunters. When the hunt triggers and the gold gets capped a few seconds later the trade goes out, using up some gold and whatever catpower has built up in that time. This way no gold or catpower gets lost.

I also noticed that at least zebra trading does not work properly during autumn. I'm assuming this has something to do with the griffin trading. Which I also can't get to work properly, as it seems to only trigger when wood, catpower and gold are all capped. In late game I'm using farmers instead of woodcutters as the biolabs boost it significantly. Because of that, wood is generally never at the cap or gets crafted the moment it is at the cap. Which means that if at that moment catpower, gold and wood are not maxed, it will not trade. Putting the wood requirement for griffin trading to 50% would remedy that problem.

**Comment by jacob-keller** [comment]
Hi

On May 13, 2015 7:22 AM, "Mewnine" <notifications@github.com> wrote:
>
> At the moment, to make sure I use up all my gold I have to deactivate
hunting. This means I am also not converting my furs into parchments when I
leave the game on for a night, so I have to save up parchment beforehand
while my mints could cover most of it. And I'm still losing gold and
catpower.
>
> A few tweaks could improve the system:
> Trading whenever the gold cap would be close and ignoring the catpower
cap would mean that all gold gets used and any overflow would go to
hunters. When the hunt triggers and the gold gets capped a few seconds
later the trade goes out, using up some gold and whatever catpower has
built up in that time. This way no gold or catpower gets lost.
>

The problem here is that you will never hunt then ever. Because we will
always go below the trigger. Or at least almost never.

> I also noticed that at least zebra trading does not work properly during
autumn. I'm assuming this has something to do with the griffin trading.
Which I also can't get to work properly, as it seems to only trigger when
wood, catpower and gold are all capped. In late game I'm using farmers
instead of woodcutters as the biolabs boost it significantly. Because of
that, wood is generally never at the cap or gets crafted the moment it is
at the cap. Which means that if at that moment catpower, gold and wood are
not maxed, it will not trade. Putting the wood requirement for griffin
trading to 50% would remedy that problem.

The problem is trying to find ways which don't starve either side. If we
put wood at 50% it is likely to end up either starving other uses of wood
or we trade it so much that we starve other uses of gold or cat power.

Our current system of being greedy with everything I think is the root of
the problem.

**Comment by Mewnine** [comment]
If you want to hunt more, add an overflow of hunters compared to geologists. Resource spending would be a lot more planned. As the current triggers cause the hunting and trading to become irregular due to the many requirements trades have at this moment to trigger properly. By tying it to gold production you can exactly calculate how much catpower is spent on trading and hunting without waste.

Resource starvation is also a matter of simply planning ahead to make sure you have more wood than required for the trade. As wood is a resource that overflows into beams and it is not lost if you have too much of it. Gold at the cap however, is just gone.

**Comment by jacob-keller** [comment]
That makes sense.

I think we can do a couple things:

The only main concern i have is getting enough parchment through. (since we only ever craft parchment when we hunt)

I propose the following changes that include your suggestions

a) have trade only check gold
b) have hunt occur after trading and reduce it's requirement so that it will hunt more often

c) I think we should come up with a way to "distribute" gold among the traded races,

ie: instead of "first come first serve", we spread it out so that if we trade with 3 races, then we give each race up to 33% of the gold

That might seem somewhat confusing, but this way, each trace would never get starved, and if you don't want it, simply disable it or set it during a different season.

Does this sound ok to you?

I suggest we document in the readme about various issues with trading/hunting.

I think we can resolve it so that we get good trading and good hunting, by lowering the catpower hunt % cap, so that we hunt lower, but always check trades first.

**Comment by jacob-keller** [comment]
If you can maybe try to pull my changes and see if these resolve your issues? That'd be great input.

Based on initial testing, everything looks great, and I haven't had fully capped gold or catpower for a while now.

I think this should resolve your concerns, as well as be much more efficient and streamlined.

**Comment by Mewnine** [comment]
Proposed changes look great, thanks for the awesome work there.

**Comment by jacob-keller** [comment]
Any particular reason go re open?

**Comment by Mewnine** [comment]
Accidentally hit reopen. As there is no implementation yet I figured I'd leave it open for now.

**Comment by cameroncondry** [comment]
A few tweaks have been made by @jacob-keller and have been pushed to master. Re-open this issue if you would like to add any information or feedback regarding the updates. I will have the changelog updated in the near future with what has been updated.
