### ISSUE TITLE
Craft scaffolds?

### ISSUE THREAD

**Issue by Azulan** [cameroncondry/cbc-kitten-scientists#8]
Can you add scaffolds to automatic crafting?

**Comment by cameroncondry** [comment]
I'm looking into a way to get more complex crafting materials into the list of auto crafted items. Main issue with scaffolds is there is no storage cap to deal with, which makes it harder to predict when to craft those items.

**Comment by trini** [comment]
I've been thinking and wishing I had better UI skills.  Perhaps adding a "tab" to the game for K-S and making checkbox/inputs for enabling build/convert X (and keep Y in reserve) along with making just Enable/Disable K-S as a front-page checkbox would help.

**Comment by cameroncondry** [comment]
A simple collapsing list may solve this, and I do like the idea of inputs for telling the system how much to use and keep on hand. Would make the system far more flexible. If all the lists can be collapsed, then there shouldn't be an issue with taking up too much vertical space from the logs.

**Comment by magus424** [comment]
Instead of basing it off a max cap, perhaps go off a percentage of the required resources?

If building a scaffold would take < 10% of the requirements (or 5% or 1% even, depending on how those work out), build one.

Or to keep both scaling upwards, only build one if a certain ratio of scaffold:requirements is met.
